# Generated by Django 4.2.10 on 2026-02-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SPECIFIED', 'Prefer not to specify')], help_text='Patient gender', max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Patient date of birth', null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Detailed medical history and conditions', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies and sensitivities', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(help_text='Clinic where the patient is registered', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
