# Generated by Django 4.2.10 on 2026-02-25 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(help_text='Link to the patient user account', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['clinic', 'user'], name='patients_pa_clinic__c5ea76_idx'),
        ),
    ]
