# Generated by Django 4.2.10 on 2026-02-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_clinic__009fa4_idx',
            old_name='patients_pa_clinic_a3b5e0_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_clinic__d06e25_idx',
            old_name='patients_pa_clinic_d2f4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_first_n_a142c0_idx',
            old_name='patients_pa_first_n_e3c6d2_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_email_bb026d_idx',
            old_name='patients_pa_email_f7a8e9_idx',
        ),
    ]
