# Generated by Django 4.2.10 on 2026-02-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_rename_patients_pa_clinic_a3b5e0_idx_patients_pa_clinic__009fa4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_clinic__009fa4_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_first_n_a142c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_email_bb026d_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor assigned to this patient (optional)', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(help_text='Patient first name', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(help_text='Patient last name', max_length=150),
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
