# Generated by Django 4.2.10 on 2026-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patientprofile_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, help_text='Patient address', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_history',
            field=models.TextField(blank=True, help_text='Clinical history and notes', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Patient date of birth', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Patient email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SPECIFIED', 'Prefer not to specify')], help_text='Patient gender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the patient', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_contact_number',
            field=models.CharField(blank=True, help_text='Alternative phone number', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'first_name', 'last_name'], name='patients_pa_clinic__1609b9_idx'),
        ),
    ]
