# Generated by Django 4.2.10 on 2026-02-25 18:42

import core.managers
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Clinic Administrator'), ('DOCTOR', 'Doctor/Orthodontist'), ('PATIENT', 'Patient')], db_index=True, default='PATIENT', help_text='User role determines access permissions', max_length=20)),
                ('contact_number', models.CharField(help_text='Primary phone number in format: +1234567890 or (123) 456-7890', max_length=20, validators=[core.validators.validate_phone_number])),
                ('secondary_contact_number', models.CharField(blank=True, help_text='Alternative phone number', max_length=20, null=True, validators=[core.validators.validate_phone_number])),
                ('address', models.TextField(blank=True, help_text='Complete physical address', null=True)),
                ('degree', models.CharField(blank=True, help_text='Professional degree (e.g., BDS, MDS, DDS, DMD)', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Not actually deleted, just marked as inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(help_text='The clinic this user belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'clinic'], name='users_custo_email_07e983_idx'), models.Index(fields=['clinic', 'role'], name='users_custo_clinic__2425ea_idx'), models.Index(fields=['is_deleted', 'clinic'], name='users_custo_is_dele_68794a_idx')],
            },
            managers=[
                ('objects', core.managers.CustomUserManager()),
            ],
        ),
    ]
