# Generated by Django 4.2.10 on 2026-02-25 18:45

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='The clinic this user belongs to (optional for admin/superuser)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Primary phone number in format: +1234567890 or (123) 456-7890', max_length=20, null=True, validators=[core.validators.validate_phone_number]),
        ),
    ]
