# Generated by Django 4.2.10 on 2026-02-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Clinic Administrator'), ('DOCTOR', 'Doctor/Orthodontist')], db_index=True, default='DOCTOR', help_text='User role determines access permissions', max_length=20),
        ),
    ]
