# Generated by Django 4.2.10 on 2026-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the dental clinic', max_length=255, unique=True)),
                ('contact_number', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('address', models.TextField(help_text='Complete physical address of the clinic')),
                ('description', models.TextField(blank=True, help_text='Description of clinic, services, etc.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this clinic is active and accepting patients')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for data retention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_deleted'], name='clinics_cli_is_acti_870910_idx')],
            },
        ),
    ]
