# Generated by Django 4.2.10 on 2026-02-25 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('BRACES', 'Traditional Braces'), ('ALIGNERS', 'Clear Aligners (Invisalign)'), ('RETAINER', 'Retainer'), ('EXTRACTION', 'Extraction'), ('SCALING', 'Scaling & Root Planing'), ('ORTHOGNATHIC', 'Orthognathic Surgery Planning'), ('PROPHYLAXIS', 'Prophylaxis (Cleaning)'), ('OTHER', 'Other')], db_index=True, help_text='Type of orthodontic treatment', max_length=50)),
                ('treatment_information', models.TextField(help_text='Detailed treatment plan and objectives')),
                ('treatment_findings', models.TextField(blank=True, help_text='Clinical findings, observations, and notes', null=True)),
                ('upload_image', models.ImageField(blank=True, help_text='Treatment documentation image (max 5MB)', null=True, upload_to='treatments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('next_visit_date', models.DateTimeField(blank=True, db_index=True, help_text='Date and time of next scheduled visit', null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('SCHEDULED', 'Scheduled')], db_index=True, default='SCHEDULED', help_text='Current status of the treatment', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(help_text='Clinic where treatment is being provided', on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['-created_at'],
            },
        ),
    ]
