# Generated by Django 4.2.10 on 2026-02-25 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this treatment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor/Orthodontist providing the treatment', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_provided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(help_text='Patient receiving the treatment', limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this treatment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['clinic', 'patient'], name='treatments__clinic__84225d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['clinic', 'doctor'], name='treatments__clinic__f5829f_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['clinic', 'status'], name='treatments__clinic__a1af72_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['next_visit_date', 'status'], name='treatments__next_vi_af9e88_idx'),
        ),
    ]
