# Generated by Django 4.2.10 on 2026-02-26 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='upload_image',
            field=models.ImageField(blank=True, help_text='Treatment documentation image (max 5MB)', null=True, upload_to='static/images/treatments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
