# Generated by Django 4.2.10 on 2026-02-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_update_patient_reference'),
        ('treatments', '0003_alter_treatment_upload_image'),
    ]

    operations = [
    ]
